### ISSUE TITLE
How would i go about running the program?

### ISSUE THREAD

**Issue by AIMads** [sign-language-processing/sign-translate#36]
## Expected Behavior
Run server locally for inference of the models
Run server locally for hosting angular website

## Actual Behavior
Can't see how to set this up and run it

## Steps to Reproduce the Problem
1. Dont have any sorry as i dont understand how to run the app

## Specifications

- Version: 18.04
- Platform: Ubuntu

My main problem is i wanna test the code out, but I cant figure out how to run it! Im mostly a python AI developer and not so much an app developer. I have identified where I need to place my own models, but can get the app running! ;)

**Comment by AmitMY** [comment]
All the scripts are available in https://github.com/sign-language-processing/sign-translate/blob/master/package.json#L4

What you need to do is:
1. `npm install` (installs all of the project's dependencies)
2. `npm start` (compiles the angular project, and serves a web-server, usually on port 4200)

**Comment by thecoder-elite** [comment]
Hey @AmitMY how to start the server to run the model

**Comment by AmitMY** [comment]
@thecoder-elite just the above two commands are needed
All of the models are client side excpet for the text-to-pose model which is server side right now, and will be moved to client side at some point soon.

**Comment by thecoder-elite** [comment]
@AmitMY thanks for replying, and this is a really good project, I and my team are also working on a similar problem statement and are currently in the research phase. I had just two question:
- what backend server is being used in this project?
- the Spoken-to-signed language translation works absolutely perfectly but the Signed-to-spoken language translation does not seem to work or maybe we are not able to use it correctly, in any case your help would be highly appreciated.

**Comment by AmitMY** [comment]
Currently, this is the server: https://github.com/IsraelKarpel/hand-sign-project/blob/main/server.py

A few things for you to note:
1. This project is GPL Licensed, meaning that any fork of it or use of its source code must as well be open source with the same license.
2. This project is still ongoing. Instead of developing something similar, you could help out on this project. See the many open issues we have.
3. The signed-to-spoken translation is not yet implemented, and will be the final component probably. It is a hard problem after all
